package cn.shgx.easy;

import java.util.HashMap;
import java.util.Map;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:e
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindtheDifference {
	 public char findTheDifference(String s, String t) {
	     Map<Character, Integer> map = new HashMap<Character,Integer>();
	     for(int i =0;i<s.length();i++) {
	    	 if(!map.containsKey(s.charAt(i))) {
	    		 map.put(s.charAt(i), 1);
	    	 }else {
	    		 map.put(s.charAt(i), map.get(s.charAt(i))+1);
	    	 }
	     }
	     for(int i =0;i<t.length();i++) {
	    	 if(!map.containsKey(t.charAt(i))) {
	    		 return t.charAt(i);
	    	 }else {
	    		 map.put(s.charAt(i), map.get(s.charAt(i))-1);
	    	 }
	     }
	     for(Character c :map.keySet()) {
	    	 if(map.get(c)!=0) {
	    		 return c;
	    	 }
	     }
	     throw new IllegalArgumentException();
	 }
	 public char findTheDifference1(String s, String t) {
	     char ans = 0;
	     for(int i =0;i<s.length();i++) {
	    	 ans^=s.charAt(i);
	     }
	     for(int i =0;i<t.length();i++) {
	    	 ans^=t.charAt(i);
	     }
	     return ans;
	 }
	 public char findTheDifference2(String s, String t) {
	     int ret = 0;
	     for(int i =0;i<s.length();i++) {
	    	ret-=(int)s.charAt(i);
	     }
	     for(int i =0;i<t.length();i++) {
	    	ret+=(int)t.charAt(i);
	     }
	     return (char)ret;
	 }
}
